# Generated by Django 3.0.2 on 2020-02-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200207_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tages',
        ),
        migrations.AddField(
            model_name='product',
            name='tages',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
