# Generated by Django 3.0.2 on 2020-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainBehavior',
            fields=[
                ('sales', models.CharField(blank=True, max_length=255, null=True)),
                ('chainname', models.CharField(db_column='chainName', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chain_behavior',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
