# Generated by Django 3.0.2 on 2020-02-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20200207_2111'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='stu_student',
        ),
    ]
